### ISSUE TITLE
Disable pinch-zoom

### ISSUE THREAD

**Issue by radare** [enwin/emoji#1]
If this is the same app as the one in the market this bug is in there..

**Comment by enwin** [comment]
It is the emoji keyboard available on the firefox marketplace :smile: 
Thanks for the issue, it was on my todo since the review on the marketplace. I'll try to fix it as soon as possible unfortunately I don't have a phone near me at the time and debugging gestures on the emulator looks challenging.

**Comment by radare** [comment]
You should be able to do that with just a meta tag to disable zoom. I can test it, but i have no time for coding, so i'll not send a pr. Sorry

**Comment by enwin** [comment]
I was thinking of the meta tag too but with no way of testing it right now I was a bit scared to push it.

I made a change in the app branch. If you can't wait you can download it, send it to you phone and tell me how it goes :smile: 

I hope this will be enough to disable the pinch zoom.

**Comment by enwin** [comment]
Fix is pending the marketplace approval!

**Comment by radare** [comment]
Cool! Thanks

**Comment by radare** [comment]
Confirm fixeness state after testing the last update from the marketplace.

Cool!
